### ISSUE TITLE
Config: mag.iua.idps is used for SAML IDPs

### ISSUE THREAD

**Issue by qligier** [i4mi/MobileAccessGateway#178]
The configuration at `mag.iua.idps` stores information about the SAML IDPs, not the IUA ones.
This is an issue if we want to support an IUA IDP (for the frontend and clients).

Currently, we have:
```yml
mag:
  iua:
    idps:
      hin:
        name: HIN eID
        metadata-url: secret/metadata_hin_test.xml
        renew-url: https://samlservices.test.epr.fed.hin.ch/saml/2.0/renewassertion
        key-alias: saml
        key-password: samlidp
        tls-key-alias: hintls
        tls-key-password: samlidp
```

I would like to change it to something like:
```yml
mag:
  idps:
    saml:
      hin:
        name: HIN eID
        metadata-url: secret/metadata_hin_test.xml
        renew-url: https://samlservices.test.epr.fed.hin.ch/saml/2.0/renewassertion
        key-alias: saml
        key-password: samlidp
        tls-key-alias: hintls
        tls-key-password: samlidp
        expose-iua: true
    iua:
      ehs:
        name: idp-ehealthsuisse
        metadata-url: https://ehealthsuisse.ihe-europe.net/iua-simulator/rest/ch/.well-known
        client-id: abc123
```
